### ISSUE TITLE
Trying to follow Microsoft Learn tutorials which reference cosmicworks

### ISSUE THREAD

**Issue by alexbenitez** [Azure-Samples/cosmicworks#27]
### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> follow MS Learn tutorial [Develop an ASP.NET web application with Azure Cosmos DB for NoSQL](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/tutorial-dotnet-web-app)

### Any log messages given by the failure
> This operation failed because it would have increased the total throughput to 4000 RU\/s

### Expected/desired behavior
> Does cosmicwork work with free cosmos db accounts? (the max is 1000 RU - can't configure to 4000)

Also, with a paid cosmos db account, I was able to upload, but I had to do so without creating any container (because the partition id - step 6- is different to the data being uploaded). Once loaded, do not get any data  when running the following query (step 21 in the Tutorial). Is there any previous version which would produce data compatible with the MS Learn tutorials?

This is from step 21 (which doesn't return data)
```
SELECT
  p.name,
  p.categoryName,
  p.tags
FROM products p
JOIN t IN p.tags
WHERE t.name = "Tag-32"
```

### OS and Version?
> Windows

### Versions
>11

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Is this tool good for MS Learn tutorials? 
Thanks

**Comment by seesharprun** [comment]
@alexbenitez, thanks for this feedback. We should have an update to the tool and tutorial later this week to resolve this.

First, the tutorial will be revamped to use v2 of the tool. The tutorial was originally using v1.

Second, the tool will be updated to support more versions of .NET to make it more universal.
